bhavani/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('cart.urls',namespace="cart")),
]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

 

 

cart/urls.py
from collections import namedtuple
from django.conf import settings
from django.urls import path
from django.conf.urls.static import static
from .views import homeview,ItemDetailView,signup,login,logout,add_to_cart,remove_from_cart,OrderSummary,remove_single_item_from_cart,Checkout,OrderedView,TotalOrderView,Productsview,payment,export_csv,delete_order,update_order,pdf_order,handlerequest

app_name="cart"
urlpatterns=[
    path('',homeview,name='home'),
    path('products',Productsview,name='products'),
    path('product/<slug>/',ItemDetailView.as_view(),name='product-detail'),
    path('add-to-cart/<slug>/',add_to_cart,name='add-to-cart'),
    path('remove-from-cart/<slug>/',remove_from_cart,name='remove-from-cart'),
    path('remove-single-item-from-cart/<slug>',remove_single_item_from_cart,name='remove-single-item-from-cart'),
    path('order-summary/',OrderSummary.as_view(),name='order-summary'),
    path('ordered/',OrderedView.as_view(),name='ordered'),
    path('checkout/',Checkout.as_view(),name='checkout'),
    path('totalorder/',TotalOrderView.as_view(),name='totalorder'),
    path('payment',payment,name='payment'),
    path('updatedelivery/<slug>',delete_order,name="delete_order"),
    path('update_order/<slug>',update_order,name="update_order"),
    path('pdf_order/<slug>',pdf_order,name="pdf_order"),
    path('export_csv',export_csv,name='export-csv'),
    path('signup/',signup,name='signup'),
    path('login/',login,name='login'),
    path('logout/',logout,name='logout'),
    path('handlerequest/',handlerequest,name='handlerequest'),
]+static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

cart/models.py
from distutils.command.upload import upload
from email.policy import default
from pyexpat import model
from django.db import models
from django.conf import settings
from django.db.models.fields import CharField
from django.shortcuts import redirect, reverse
from django.contrib.auth.models import User
import uuid
 
CATEGORY_CHOICES = (
    ('Cashew','Cashew'),
    ('Grapes','Grapes'),
    ('Icecream','Icecream'),
)
STYLE_CHOICES=(
    ('R','RECTANGLE'),
    ('RO','ROUND'),
)

# Create your models here.
class Category(models.Model):
    name=models.CharField(max_length=100)

    def __str__(self):
        return self.name

class Items(models.Model):
    title=models.CharField(max_length=200)
    dis_price=models.FloatField()
    originalprice=models.FloatField(blank=True,null=True)
    category=models.ForeignKey(Category,blank=True,null=True,on_delete=models.CASCADE)
    description=models.CharField(max_length=1000,blank=True,null=True)
    frame_type=models.CharField(max_length=100,blank=True,null=True)
    style=models.CharField(choices=STYLE_CHOICES,default='RECTANGLE',max_length=100)
    color=models.CharField(max_length=20,default="black")
    image=models.ImageField(upload_to='media/',blank=True)
    slug=models.SlugField()

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("cart:product-detail",kwargs={
            'slug': self.slug
        })

    def get_add_to_cart(self):
        return reverse("cart:add-to-cart",kwargs={
            'slug':self.slug
        })  

    def get_remove_from_cart(self):
            return reverse("cart:remove-from-cart",kwargs={
            'slug':self.slug
        }) 


    

    



class OrderItem(models.Model):
    user=models.ForeignKey(settings.AUTH_USER_MODEL,on_delete=models.CASCADE)
    ordered=models.BooleanField(default=False)
    item=models.ForeignKey(Items,on_delete=models.CASCADE)
    quantity=models.IntegerField(default=1)
        

    def __str__(self):
        return self.item.title       

    def get_total_item_price(self):
        return self.quantity * self.item.dis_price   

class BillingAddress(models.Model):
    user=models.ForeignKey(User,on_delete=models.CASCADE)
    billingname=models.CharField(max_length=200)
    address_1=models.CharField(max_length=300)
    address_2=models.CharField(max_length=300)
    city=models.CharField(max_length=200)
    district=models.CharField(max_length=100)
    zip_code=models.CharField(max_length=10)
    phonenumber=models.BigIntegerField()
    

    def __str__(self):
        return f"{self.user.username} {self.id}"
   

     


class Order(models.Model):
    user=models.ForeignKey(settings.AUTH_USER_MODEL,on_delete=models.CASCADE)
    ordered=models.BooleanField(default=False)
    items=models.ManyToManyField(OrderItem)
    start_date=models.DateTimeField(auto_now_add=True)
    ordered_date=models.DateTimeField()
    total_price=models.FloatField(blank=True,null=True)
    billingaddress=models.OneToOneField(BillingAddress,on_delete=models.CASCADE,null=True)
    delivered=models.BooleanField(default=False)
    

    def __str__(self):
        return f"{self.user.username}  {self.id}"

    def get_total(self):
        total = 0
        for order_item in self.items.all():
            total = total+order_item.get_total_item_price()
        self.total_price=total    
        return total



    def get_update_order(self):
        return reverse("cart:update_order",kwargs={
            'slug':self.id
        })    

    def get_pdf_order(self):
        return reverse("cart:pdf_order",kwargs={
            'slug':self.id
        })    

     

         
class TotalOrder(models.Model):
    totalorder=models.ManyToManyField(Order)


    def __str__(self):
        return f"{self.id}"

    def get_delete_order(self):
            return reverse("cart:delete_order",kwargs={
            'slug': self.id
        })    
   
    


        


class UserOtp(models.Model):
    phonenumber=models.BigIntegerField(blank=True,null=True)
    user=models.ForeignKey(User,on_delete=models.CASCADE)
    otp=models.IntegerField(blank=True,null=True)    
       


          
 



    


 

cart/forms.py
from django import forms

DISTRICT = (
    ('', 'Choose...'),
    ('dwd', 'Dharwad'),
    ('belgaum', 'Belgaum'),
    ('RJ', 'Bangalore')
)
 

class AddressForm(forms.Form):
    billingname=forms.CharField(label='billingname')
    address_1 = forms.CharField(
        label='Address',
        widget=forms.TextInput(attrs={'placeholder': '1234 Main St'})
    )
    address_2 = forms.CharField(
        widget=forms.TextInput(attrs={'placeholder': 'Apartment, studio, or floor'})
    )
    city = forms.CharField()
    district = forms.ChoiceField(choices=DISTRICT)
    zip_code = forms.CharField(label='Zip')
    phone_number=forms.IntegerField(widget=forms.TextInput(attrs={'placeholder': '+91:'}))
    check_me_out = forms.BooleanField(required=True)


 

cart/views.py
from django.http import response
from django.http.response import JsonResponse
from django.shortcuts import render,redirect,get_object_or_404
from django.views.generic import DetailView,ListView,View
from .models import BillingAddress, Category,Items,Order,OrderItem,TotalOrder, UserOtp
from .forms import AddressForm
from django.core.exceptions import ObjectDoesNotExist
from django.contrib.auth.decorators import login_required
from django.contrib.admin.views.decorators import staff_member_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.models import User,auth
from django.contrib import messages
from django.http import HttpResponse, request
from django.contrib.sites.shortcuts import get_current_site
from django.utils import timezone
from django.core.mail import send_mail
from django.urls import reverse
from django.template.loader import get_template
from xhtml2pdf import pisa
import csv
import datetime
import random
from bhavani import settings
from django.views.decorators.csrf import csrf_exempt

# Create your views here.
def homeview(request):
    if request.method=='POST':
        search_element=request.POST.get('product')
        items=Items.objects.filter(title=search_element)
        if search_element=='':
            items=Items.objects.all()
        categories=Category.objects.all()
        context={
            'object_list':items,
            'categories':categories
        }
        return render(request,"cart/home.html",context)
        
    else:        
        category=request.GET.get('category')
        if category=='none':
            items=Items.objects.all()
        else:
            items=Items.objects.filter(category__name=category)   

        if category is None:
            items=Items.objects.all()    

        #search
        if 'term' in request.GET:
            qs=Items.objects.filter(title__icontains=request.GET.get('term'))
            titles= list()
            for product in qs:
                titles.append(product.title)
            return JsonResponse(titles,safe=False)    
            
        categories=Category.objects.all()
        context = {
            'object_list':items,
            'categories':categories
        }    
        return render(request,"cart/home.html",context)
    



def Productsview(request):
    category=request.GET.get('category')
    if category=='none':
        items=Items.objects.all()
    else:
        items=Items.objects.filter(category__name=category)   

    if category is None:
        items=Items.objects.all()    
        
    categories=Category.objects.all()
    context = {
        'object_list':items,
        'categories':categories
    }
    return render(request,"cart/products.html",context)








class OrderSummary(LoginRequiredMixin,View):
    login_url="/login"
    def get(self,*args,**kwargs):
        try:
            order = Order.objects.get(user=self.request.user,ordered=False)
            context={
                'object': order
            }
            return render(self.request,"cart/order-summary.html",context)

        except ObjectDoesNotExist:
            messages.info(self.request,'You dont have any active order')
            return redirect('/')

        return render(self.request,"cart/order-summary.html")

# Adding Payment Gateway
import razorpay
razorpay_client = razorpay.Client(auth=(settings.razorpay_id, settings.razorpay_account_id))

@csrf_exempt
def handlerequest(request):
            messages.success(request,'Your order is placed Succesfully')
            return redirect('/')   
       

class Checkout(LoginRequiredMixin,View):
    login_url="/login"
    def get(self,*args,**kwargs):
        order =get_object_or_404(Order,user=self.request.user,ordered=False)
        form=AddressForm()
        context={
           'object': order,
           'form':form
        } 
        return render(self.request,"cart/checkout.html",context)


    def post(self,*args,**kwargs):
        form=AddressForm(self.request.POST or None)
        if form.is_valid():
            billingname=form.cleaned_data['billingname']
            address_1=form.cleaned_data['address_1']
            address_2=form.cleaned_data['address_2']
            city=form.cleaned_data['city']
            district=form.cleaned_data['district']
            zip_code=form.cleaned_data['zip_code']
            phone_number=form.cleaned_data['phone_number']
            order=get_object_or_404(Order,user=self.request.user,ordered=False)
            billing_address=BillingAddress.objects.create(user=self.request.user,billingname=billingname,address_1=address_1,address_2=address_2,city=city,district=district,zip_code=zip_code,phonenumber=phone_number)
            
            order.ordered=True
            order.billingaddress=billing_address
            order.total_price=order.get_total()
            for order_item in order.items.all():
                order_item.ordered=True
                order_item.save()

            total_order=TotalOrder.objects.create()
            total_order.totalorder.add(order)
            order.save()
                  #payment
        callback_url = 'http://127.0.0.1:8000/handlerequest/'
        print(callback_url)
        notes = {'order-type': "basic order from the website", 'key':'value'}
        razorpay_order = razorpay_client.order.create(dict(amount=order.total_price*100, currency='INR', notes = notes, receipt=f"{order.id}", payment_capture='0'))
        print(razorpay_order['id'])
        order.razorpay_order_id = razorpay_order['id']
        order.save()

        return render(self.request, 'cart/paymentsummaryrazorpay.html', {'order':order, 'order_id': razorpay_order['id'], 'orderId':order.id, 'total_price':order.total_price, 'razorpay_merchant_id':settings.razorpay_id, 'callback_url':callback_url})

        ##
            # mess=f"New order from {self.request.user.first_name} Order Id is {total_order.id} Total price:{order.total_price}  Please Check ASAP"
            # send_mail('New Order',mess,'singamhari34@gmail.com',['raohari12@gmail.com'],fail_silently=False)
            # mess1=f"Your Order has been placed succesfully"
            # send_mail('Greetings!',mess1,'raohari12gmail.com',[self.request.user.email],fail_silently=False)
            # messages.success(self.request,'your order is placed succesfully')
          

            
             

class OrderedView(LoginRequiredMixin,ListView):
    login_url="/login"
    template_name="cart/ordered.html"
    def get_queryset(self):
        return Order.objects.filter(user=self.request.user)
    


     
            
class ItemDetailView(DetailView):
    model = Items
    template_name="cart/product-detail.html"

 
class TotalOrderView(LoginRequiredMixin,ListView):
    login_url="/admin"
    template_name="cart/totalorder.html"  
    def get_queryset(self):
        user=self.request.user
        if(user.is_superuser):
            return TotalOrder.objects.all().order_by('-id')
        else:
            return 


    def post(self,*args,**kwargs):
        search=self.request.POST['search']
        if search=='':
            totalorder=TotalOrder.objects.all()
        
        else:    
            totalorder=TotalOrder.objects.filter(id=search) 
        context={
            'object_list':totalorder
        }
        return render(self.request,"cart/totalorder.html",context)
        
    
     


def signup(request):
    if request.method=='POST':
        get_otp=request.POST.get('otp')
        if get_otp:
            get_usr=request.POST['user']
            usr=User.objects.get(username=get_usr)
            if int(get_otp)==UserOtp.objects.filter(user=usr).last().otp:
                usr.is_active=True
                usr.save()
                return redirect('/login')
            else:
                messages.warning(request,"OTP is invalid")
                return render(request,'cart/signup.html',{'otp':True,'user':usr})

        else:
        
            first_name=request.POST['first_name']
            last_name=request.POST['last_name']
            password1=request.POST['password1']
            password2=request.POST['password2']
            email=request.POST['email']
            
            if password1==password2:    
                if User.objects.filter(email=email).exists(): 
                    messages.info(request,'Email Taken')
                    return redirect('/signup')


                    
                else:
                    user=User.objects.create_user(username=email,first_name=first_name,last_name=last_name,password=password1,email=email)
                    user.save()
                    otp=random.randint(100000,999999)
                    userotp=UserOtp.objects.create(user=user,otp=otp)

                    mess=f"{user.first_name} Your otp is {otp}"
                    send_mail('Welcome',mess,'ss',[email],fail_silently=False)
                    return render(request,'cart/signup.html',{'otp':True,'user':user})


            else:
                messages.info(request,'password mismatch')
                return render(request,'cart/signup.html')


    else:
        return render(request,'cart/signup.html')


def login(request):
    if request.method=='POST':
        username=request.POST['username']
        password=request.POST['password']

        user=auth.authenticate(username=username,password=password)
        if user is not None:
            auth.login(request,user)
            return redirect('/')

        else:
            messages.info(request,'Invalid Credentials')
            return redirect('/login')    

    else:
        
        return render(request,'cart/login.html')


def logout(request):
    auth.logout(request)      
    return redirect('/')

@login_required(login_url='/login')
def add_to_cart(request,slug):
    item=get_object_or_404(Items,slug=slug)
    order_item, created = OrderItem.objects.get_or_create(
        item=item,
        user=request.user,

cart/templates/cart/aboutus.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-eOJMYsd53ii+scO/bJGFsiCZc+5NDVN2yr8+0RDqr0Ql0h+rP48ckxlpbzKgwra6" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'cart/styles.css' %}" type="text/css">
    <title>About Us</title>
</head>
<body>
    <div class="aboutus p-3 text-center" id="aboutus">
   <b> ABOUTS US</b>
   <p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum</p>
    </div>
</body>
</html>

cart/templates/cart/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-eOJMYsd53ii+scO/bJGFsiCZc+5NDVN2yr8+0RDqr0Ql0h+rP48ckxlpbzKgwra6" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'cart/styles.css' %}" type="text/css">
    <link
    rel="stylesheet"
    href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/4.1.1/animate.min.css"
  />
  <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    <title>Document</title>
</head>
<body>  
  

   
        <nav class="navbar navbar-expand-md navbar-dark bg-dark fixed-top"> 
          <div class="container">
             
              <a class="navbar-brand" href="/">
                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-house-door-fill" viewBox="0 0 16 16">
                <path d="M6.5 14.5v-3.505c0-.245.25-.495.5-.495h2c.25 0 .5.25.5.5v3.5a.5.5 0 0 0 .5.5h4a.5.5 0 0 0 .5-.5v-7a.5.5 0 0 0-.146-.354L13 5.793V2.5a.5.5 0 0 0-.5-.5h-1a.5.5 0 0 0-.5.5v1.293L8.354 1.146a.5.5 0 0 0-.708 0l-6 6A.5.5 0 0 0 1.5 7.5v7a.5.5 0 0 0 .5.5h4a.5.5 0 0 0 .5-.5z"/>
              </svg>
            </a>
              <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
              </button>
              <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav">
                  {% if user.is_authenticated %}
                  <li class="nav-item text-info mt-2">
                    <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-person-circle" viewBox="0 0 16 16">
                      <path d="M11 6a3 3 0 1 1-6 0 3 3 0 0 1 6 0z"/>
                      <path fill-rule="evenodd" d="M0 8a8 8 0 1 1 16 0A8 8 0 0 1 0 8zm8-7a7 7 0 0 0-5.468 11.37C3.242 11.226 4.805 10 8 10s4.757 1.225 5.468 2.37A7 7 0 0 0 8 1z"/>
                    </svg>
                       Hello,  {{user.first_name}} 
  
                  </li>
                  {% endif %}
                  <li class="nav-item">
                    <a class="nav-link " href="{% url 'cart:products'%}">  Products</a>
                  </li>
                   
                
                  {% if user.is_staff %}
                  <li class="nav-item">
                    <a class="nav-link" href="{% url 'cart:totalorder'%}">Total Orders</a>
                  </li>
                  {% endif %}
                </ul>
                <ul class="navbar-nav ms-auto"> 
                    {% if user.is_authenticated %}
                    <li class="nav-item">
                      <a class="nav-link" href="{% url 'cart:ordered'%}">Your Orders</a>
                    </li>
                    
                    <li class="nav-item ">
                      <a href="{% url 'cart:order-summary' %}" class="nav-link">
                      <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-cart3" viewBox="0 0 16 16">
                          <path d="M0 1.5A.5.5 0 0 1 .5 1H2a.5.5 0 0 1 .485.379L2.89 3H14.5a.5.5 0 0 1 .49.598l-1 5a.5.5 0 0 1-.465.401l-9.397.472L4.415 11H13a.5.5 0 0 1 0 1H4a.5.5 0 0 1-.491-.408L2.01 3.607 1.61 2H.5a.5.5 0 0 1-.5-.5zM3.102 4l.84 4.479 9.144-.459L13.89 4H3.102zM5 12a2 2 0 1 0 0 4 2 2 0 0 0 0-4zm7 0a2 2 0 1 0 0 4 2 2 0 0 0 0-4zm-7 1a1 1 0 1 1 0 2 1 1 0 0 1 0-2zm7 0a1 1 0 1 1 0 2 1 1 0 0 1 0-2z"/>
                        </svg> Cart
                      </a>
                       </li>
                       <li class="nav-item">
                        <a href="/logout" class="nav-link">Logout</a>
                         
                    </li>
                    {% else %}
                    <li class="nav-item">
                      <a href="/admin" class="nav-link">Admin Login</a>
                       
                  </li>
                    <li class="nav-item">
                        <a href="/signup" class="nav-link">Signup</a>
                         
                    </li>
                    <li class="nav-item">
                      
                        <a href="/login" class="nav-link"><svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-box-arrow-in-right" viewBox="0 0 16 16">
                          <path fill-rule="evenodd" d="M6 3.5a.5.5 0 0 1 .5-.5h8a.5.5 0 0 1 .5.5v9a.5.5 0 0 1-.5.5h-8a.5.5 0 0 1-.5-.5v-2a.5.5 0 0 0-1 0v2A1.5 1.5 0 0 0 6.5 14h8a1.5 1.5 0 0 0 1.5-1.5v-9A1.5 1.5 0 0 0 14.5 2h-8A1.5 1.5 0 0 0 5 3.5v2a.5.5 0 0 0 1 0v-2z"/>
                          <path fill-rule="evenodd" d="M11.854 8.354a.5.5 0 0 0 0-.708l-3-3a.5.5 0 1 0-.708.708L10.293 7.5H1.5a.5.5 0 0 0 0 1h8.793l-2.147 2.146a.5.5 0 0 0 .708.708l3-3z"/>
                        </svg>Login</a>
                         
                    </li>
                    {% endif %}
                  
     
                   
                </ul>
              </div>
            </div>
          </nav>

        
        {% if messages %}
    {% for message in messages %}
    <div class="alert alert-primary" role="alert">
         {{message}}
      </div>
    {% endfor %}
{% endif %}


<!-- Scripts -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/js/bootstrap.bundle.min.js" integrity="sha384-JEW9xMcG8R+pH31jmWH6WWP0WintQrMb4s7ZOdauHnUtxwoG2vI5DkLtS3qm9Ekf" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.1/dist/umd/popper.min.js" integrity="sha384-SR1sx49pcuLnqZUnnPwx6FCym0wLsk5JZuNx2bPPENzswTNFaQU1RDvt3wT4gWFG" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/js/bootstrap.min.js" integrity="sha384-j0CNLUeiqtyaRmlzUHCPZ+Gy5fQu0dQ6eZ/xAww941Ai1SxSY+0EQqNXNE6DZiVc" crossorigin="anonymous"></script>        
</body>
{% block content%}
{% endblock content%}
</html>

cart/templates/cart/products.html
{% extends "cart/base.html"%}
{% load static %}
{% block content %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'cart/styles.css' %}" type="text/css">
    <title>Product</title>
    
</head>
<body  >
  <h1 class="text-center p-3"><b>EYE WEAR</b></h1>
  <div class="btn-group px-5 mx-5 mb-2" style="float: right;">
    <button type="button" class="btn btn-info dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
      Filter
    </button>
    <div class="dropdown-menu">
      <a href="{% url 'cart:products'%}?category=none" class="dropdown-item">All</a>
      {% for category in categories%}
      <a href="{% url 'cart:products'%}?category={{category.name}}" class="dropdown-item">{{category.name}}</a>
      {%endfor%}
       
    </div>
  </div>

   
  <div class="container">
    <div class="card-group">
      <hr>
      {% for item in object_list %}
      <div class="col-sm-12 col-lg-4" style="padding: 01cm;">
      <div class="card">
          
          <div class="card-body">
            <a href="{{ item.get_absolute_url }}" class="link-dark no-underline text-warning p-2"> <b>{{item.title}}</b> </a>
            <p class="text-success"> <b>Categerory: {{item.category}}</b></p>
            <p class="text-success"> <b>Size: {{item.size}}</b></p>
            <h5 class="card-text"><b>&#x20B9;{{item.discountedprice}}</b><del style="color: rgb(58, 57, 57); padding-left: .5cm;">{{item.price}}</del></h5>
            <a href="{{item.get_add_to_cart}}" class="btn btn-dark" style="float:right;">Add to cart</a>
             
  
          </div>
        </div>
      </div>
      {% empty %}
      <h2 class="m-5 p-5">Search with proper name of the product<a href="{% url 'cart:home'%}?category=none" >Click here to show all products</a></h2>
      {% endfor %}
      </div>
  </div>
</body>
</html>
{% include "cart/footer.html"%}
{% endblock %}